/**
 * Site-wide identity for this open directory.
 *
 * Generated by pnpm run setup — edit here (or rerun setup) to rebrand.
 * Keep every key here, not scattered across components: pages, feeds, API
 * metadata and scrapers all read from this one object.
 */
export const siteConfig = {
  /** Human name of the site, e.g. "Op Shop Directory". */
  name: 'US Open Data',
  /** Singular label for one listing, e.g. "op shop". */
  thing: 'open data source',
  /** Plural label for listings, e.g. "op shops". */
  thingPlural: 'open data sources',
  /** The city the directory starts in, e.g. "Wellington". */
  city: 'United States',
  /** Broader region label, e.g. "Wellington region". */
  region: 'United States',
  /** Public base URL. Defaults to empty in dev; override with NEXT_PUBLIC_SITE_URL. */
  baseUrl: 'https://awesome-open-usa-data.vercel.app',
  /** GitHub repo `<owner>/<repo>` used for community issue links. Empty = links hidden. */
  ghRepo: 'olitreadwell/awesome-open-usa-data',
  /** Contact email shown in footers and docs. */
  contactEmail: '',
  /** Days after `lastVerified` before a listing shows as stale. */
  staleAfterDays: 180,
  /** Vercel cron schedule for the daily refresh, in UTC. 2am NZT = 14:00 UTC. */
  refreshSchedule: '0 14 * * *',
};

/**
 * Resolve site identity, applying the `NEXT_PUBLIC_SITE_URL` env override
 * onto the committed defaults so a preview deployment keeps its own URL.
 *
 * @returns The effective site config.
 */
export function getSiteConfig() {
  return {
    ...siteConfig,
    baseUrl: process.env.NEXT_PUBLIC_SITE_URL ?? siteConfig.baseUrl,
  };
}
